### PR TITLE
Improve h1 font and footer coloring using a theme fork

### PR DESCRIPTION
**Pull request by gonzaloserrano**
before (left) vs after (right)
out

### CODE REVIEW

**Comment by gonzaloserrano** [comment]
@smoya basically I tried to mimic the logo font for the h1's

**Comment by gonzaloserrano** [comment]
maybe need a better letter-space, let me try

**Comment by gonzaloserrano** [comment]
localhost_1313_

**Comment by smoya** [comment]
Now looks much better 👏 !

Btw, you can easily check by using Netlify previews:

Old: https://5e98bf37142dcc0006ca88d5--bcneng.netlify.app/
New: https://5e9991bf63bb3600065cfbaf--bcneng.netlify.app/

**Comment by smoya** [comment]
Ready to go 🚀 @gonzaloserrano

**Pull request merged**
